const CANVAS_WIDTH = 650;
const CANVAS_HEIGHT = 550;
const ARROW_RIGHT = 39;
const ARROW_DOWN = 40;
const ARROW_LEFT = 37;
const ARROW_UP = 38;
const SPACE_BAR = 32;
const LETTER_P = 80;
let obstacleImg = [];
let powerUpImg;
let score = 0;
let highestScore = 0;
const scoreEl = document.getElementById("scoreEl");
const scoreResultEl = document.getElementById("score-result");
const highestScoreResultEl = document.getElementById("highest-score-result");
const timeElement = document.getElementById("chronometer-watch");
const gameResultLoss = document.getElementById("lost");
const gameResultWin = document.getElementById("win");
