const CANVAS_WIDTH = 750;
const CANVAS_HEIGHT = 650;
const ARROW_RIGHT = 39;
const ARROW_DOWN = 40;
const ARROW_LEFT = 37;
const ARROW_UP = 38;
const SPACE_BAR = 32;
let obstacleImg;
let powerUpImg;
let score = 0;
const scoreEl = document.getElementById("scoreEl");
const timeElement = document.getElementById("chronometer-watch");
